# To use the MeowCop gem.
inherit_gem:
  meowcop:
    - config/rubocop.yml


# You can customize rubocop settings.
# For example.

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
